apiVersion: v1
kind: Secret
metadata:
  name: grafana-telegram
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
stringData:
  TELEGRAM_BOT_TOKEN: "8472128176:AAHu4RPEfDA__rHJf9rrswKZZw_4ptHk_aI"
  TELEGRAM_CHAT_ID: "-1003043442042"
